peft_model:
  id: iusztinpaul/fin-falcon-7b-lora:1.0.5
model:
  id: tiiuae/falcon-7b-instruct
  template_name: "falcon"
  max_new_tokens: 500
  temperature: 1.0
setup:
  device: cuda:0
  debug: False
dataset:
  file: "testing_data.json"