name: Destroy AWS Infrastructure

on: [workflow_dispatch]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPOSITORY_NAME: streaming_pipeline

jobs:
  deploy:
    name: Destroy AWS infrastructure for the Streaming Pipeline
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install GNU Make
      id: install_make
      run: sudo apt-get update && sudo apt-get install -y make

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Destroy AWS infrastructure
      id: undeploy_aws
      working-directory: ./modules/streaming_pipeline
      run: make undeploy_aws
